### ISSUE TITLE
hardcoded sudo

### ISSUE THREAD

**Issue by teadur** [Mooash/nagios-nrpe-server#11]
It seems to me that your role has hardcoded dep on sudo for system, why is that and are you planning to remove it ?

**Comment by Mooash** [comment]
Hey, great question. I've never really considered not needing sudo. Are you able to give some examples where specifying it would break the playbook?

The reason I include is that the systems that I run this on sometimes require sudo (for when I'm not running it as root, but SSHing in as another user). It also means if I include it in a global playbook I don't have to specify for it to be ran via sudo.

**Comment by Mooash** [comment]
Looking back at this, I agree its a bad idea. I'm going to remove it soon so that its up to the playbook that this role is included in to run it through sudo if required.
